POST http://localhost:8080/api/updatePassword HTTP/1.1
content-type: application/json

{
    "uuid": "6967d980-f581-11e8-a3e3-7197df1fa3a0",
    "old_password": "1",
    "new_password": "hola",
    "new_password_repeat": "hola"
}