POST http://localhost:8080/api/joinChannel/ HTTP/1.1
content-type: application/json

{
    "uuid": "e202c340-57c0-11e9-a9ca-3c0e017b2d69", 
    "channel": "89ad2770-5799-11e9-9646-f826cfc2f55e"
}